config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admins'=> 'devise/registrations#update', :as => 'admin_registration'
     get 'admin/users' => 'admin/users#index'
  end

  namespace :admin do
    resources :users, only: [:new, :create, :destroy]
  end

  devise_for :users 
  

   resources :artworks do 
    collection do 
      get 'search'
    end
    resources :purchases
    member do 
     get "like", to: "artworks#upvote"
     get "dislike", to: "artworks#downvote"
    end
    resources :comments
  end

     root 'artworks#index'
   

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
	has_many :comments
	belongs_to :category
  has_many :purchases
	
	has_attached_file :image, styles: {medium: "300x300#", large: "800x700>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :caption, presence: true,
            length: {minimum: 3}

  validates :description, presence: true,
            length: {minimum: 10}

  validates :image, presence: true

  validates :category_id, presence: true

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :artworks, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :artwork
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :artwork
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :artworks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :purchases

  has_attached_file :profile_pic, styles: {small: "50x50",medium: "300x300#", large: "600x500>"}
  validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
          
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # check to make sure user is admin
  before_filter :authenticate_admin!
  before_action :find_user_params, only: [:show, :destroy]

  def index
    @users=User.all
  end

  def new
  end

  def show
  end

  def create
    @user=User.new(artist_params)
    raw_password = SecureRandom.hex
    @user.password= raw_password
    @user.artist= true

    if @user.save
      #ArtistMailer.sign_up_artist(@user).deliver_now
      # TODO: Email them their password, which is captured in raw_password.
      # Success flash message
      redirect_to admin_users_path, notice: 'Artist successfully created!'
    else
      # Error flash message
      render 'new'
    end
  end


  def destroy
    # Getting a bad guy off our back.
    @user.destroy
    redirect_to admin_users_path
  end


  private

    # def make_sure_user_is_admin
      
    # end

    def find_user_params
      @user= User.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:email, :username, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username

    devise_parameter_sanitizer.for(:account_update) << :profile_pic


    devise_parameter_sanitizer.for(:sign_up) << :artist
  end

  def after_sign_up_path_for(resource)
    if current_user.artist?
    artworks_path
    else
    root_path
    end
  end

  def after_sign_in_path_for(resource)
    if current_user.artist?
      artworks_path
    else
      root_path
    end
  end

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
	before_action :find_artwork, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]


  # def search
  #   # if @q=Artwork.ransack(params[:q])
  #   #   @artworks= @q.result(distinc: true)
  #   else
  #     @artworks=Artwork.all
  #   end
  # end
  
	def index
  if params[:category].blank?
		@artworks=Artwork.all.order('created_at DESC')
    # if @search=Artwork.search(params[:q])
    #   @artworks = @search.result(distinc: true)
    else
      @category_id= Category.find_by(name: params[:category]).id
      @artworks= Artwork.where(category: @category_id).order('created_at DESC')
    end
	end

	def show
		@comments=Comment.where(artwork_id: @artwork)
    @artworks=Artwork.all.order('created_at DESC')
	end

	def new
		@artwork=current_user.artworks.build
	end

	def create
		@artwork=current_user.artworks.build(artwork_params)

		if @artwork.save
			redirect_to @artwork
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @artwork.update(artwork_params)
			redirect_to @artwork
		else
			render 'edit'
		end
	end

	 def destroy
	 	@artwork.destroy
	 	redirect_to root_path
	 end

	def upvote
    @artwork.upvote_by current_user
    redirect_to :back
  end

  # def downvote
  #   @artwork.downvote_by current_user
  #   redirect_to :back
  # end

	
	private

	def find_artwork
		@artwork=Artwork.find(params[:id])
	end

	def artwork_params
		params.require(:artwork).permit(:caption, :description, :image, :category_id, :price)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
	def create
		@artwork=Artwork.find(params[:artwork_id])
		@comment=current_user.comments.build(comment_params)
		@comment.artwork_id=@artwork.id 

		if @comment.save
			redirect_to artwork_path(@artwork)
		else
			render 'new'
		end
	end

  def destroy
    @artwork=Artwork.find(params[:artwork_id])
    @comment=@artwork.comments.find(params[:id])
    @comment.destroy
    redirect_to @artwork
  end
	


	private

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!

  def new
    @purchase= current_user.purchases.build
  end

  def show
  end

  def create
    @artwork=Artwork.find(params[:artwork_id])
    @purchase= current_user.purchases.build
    @purchase.artwork_id= @artwork.id
    

    if @purchase.save
      redirect_to artwork_path(@artwork)
    else
      redirect_to artwork_path(@artwork)
    end
  end 




end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<h2>Create a new user</h2>
<%= form_tag action: :create do |f| %>
  <div><%= text_field :email, nil, name: "artist[email]", placeholder: "Artist's email address" %></div>
  <div><%= text_field :username, nil, name: "artist[username]", placeholder: "Artist's username" %></div>
  <div><%= submit_tag nil, value: "Create new artist" %></div>
<% end %>

app/views/admin/users/index.html.erb
<% @users.each do |user| %>
<%= user.username %>
<%= user.email %>
<%= link_to 'Delete Artist', admin_user_path(user), method: :delete, 
        data: {confirm: 'Are you sure you want to delete this artist?'} %>
<% end %>

app/views/admin/users/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', root_path %>

app/views/artworks/_form.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Upload/Edit your artwork</h3>
      </div>
      <div class="panel-body">
        <%= simple_form_for @artwork  do |f| %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "select a category"} %>
        <%= f.input :image %>
        <%= f.input :caption %>
        <%= f.input :description %>
        <%= f.input :price %>
        
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artworks/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<%= render 'form' %>
</div>

app/views/artworks/index.html.erb
<%# if user_signed_in? %>
<%# if current_user.artist? %>
<%#= link_to 'Upload your artwork here!', new_artwork_path %>
<%# end %>
<%# end %>




<!-- <div class="container" style="margin-top: 20px;">
 <% flash.each do |name, msg| %>
 <%= content_tag :div, msg, class: "alert alert-info"  %>
 <% end %> 
</div>
 -->


<header id="myCarousel" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for Slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <!-- Set the third background image using inline CSS below. -->
                    <div class="fill slide1"></div>
                    <div class="carousel-caption">
                      <div class="carousel-caption">
                        <div class="col-lg-12">
                            <div class="intro-message">
                                <h1 class="wow bounceIn"  data-wow-iteration="2"><span class="afrikart">Welcome to AfrikART</span></h1>
                                <h3 class="afrikart1">Unveiling Africa's hidden art talent.</h3>
                                <hr class="intro-divider">
                                <!-- <ul class="list-inline intro-social-buttons">
                                    <li>
                                        <a href="https://twitter.com/ayinloya" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                                    </li>
                                    <li>
                                        <a href="https://ayinloya.github.io" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                                    </li>
                                    <li>
                                        <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                                    </li>
                                </ul> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="item">
                    <!-- Set the third background image using inline CSS below. -->
                    <div class="fill slide2"></div>
                    <div class="carousel-caption">
                      <div class="carousel-caption">
                        <div class="col-lg-12">
                            <div class="intro-message">
                                <h1 class="wow bounceIn"  data-wow-iteration="2"><span class="afrikart">Where artists and artlovers meet.</span></h1>
                                <!-- <h3>Accomplish everyday tasks in style</h3> -->
                                <hr class="intro-divider">
                                <!-- <ul class="list-inline intro-social-buttons">
                                    <li>
                                        <a href="https://twitter.com/ayinloya" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                                    </li>
                                    <li>
                                        <a href="https://ayinloya.github.io" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                                    </li>
                                    <li>
                                        <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                                    </li>
                                </ul> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                <div class="item">
                    <!-- Set the third background image using inline CSS below. -->
                    <div class="fill slide3"></div>
                    <div class="carousel-caption">
                      <div class="carousel-caption">
                        <div class="col-lg-12">
                            <div class="intro-message">
                                <h1 class="wow bounceIn"  data-wow-iteration="2"><span class="afrikart">Where the language spoken is art.</span></h1>
                                <!-- <h3>Accomplish everyday tasks in style</h3> -->
                                <hr class="intro-divider">
                                <!-- <ul class="list-inline intro-social-buttons">
                                    <li>
                                        <a href="https://twitter.com/ayinloya" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                                    </li>
                                    <li>
                                        <a href="https://ayinloya.github.io" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                                    </li>
                                    <li>
                                        <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                                    </li>
                                </ul> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <!-- Set the fourth background image using inline CSS below. -->
                <div class="fill slide4"></div>
                <div class="carousel-caption">
                  <div class="carousel-caption">
                    <div class="col-lg-12">
                        <div class="intro-message">
                            <h1 class="wow bounceIn"  data-wow-iteration="2">
                            <span class="afrikart">Join the art community.</span></h1>
                            <!-- <h3>Apt to the rescue, whether you're preparing food or making emergency repairs </h3> -->
                            <hr class="intro-divider">
                            <!-- <ul class="list-inline intro-social-buttons">
                                <li>
                                    <a href="https://twitter.com/ayinloya" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                                </li>
                                <li>
                                    <a href="https://ayinloya.github.io" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                                </li>
                                <li>
                                    <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                                </li>
                            </ul> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>

    <br>


<div class="container">
  <section><!-- 
  <div class="page-header"><h1 class="text-center" id="header">Artworks</h1></div> -->
    <div class="row">
      <% @artworks.each do |artwork| %>
      <div class ="col-xs-6 col-sm-6 col-md-3 col-lg-3">
        <div class="panel panel-default">
          <div class="panel-bodyy">
            <%=link_to (image_tag artwork.image.url(:medium), class: 'img-responsive'), artwork %>
          </div>
          <div class="panel-footer">
            <p><%=link_to artwork.caption,artwork,class: 'caption'%></p>
            <hr>
            <p>Artwork by
              <%= link_to artwork.user.username %></p>

              <%#= pluralize(artwork.likes.count, "Like") %>
              <hr>
              <p class="pos"><%= number_to_currency(artwork.price) %><!-- <i class="fa fa-cart-arrow-down fa-2x"></i> --></p>
              <div class="row">
            <!-- <div class="pull-left">
               <p><%= number_to_currency(artwork.price) %></p>
             </div> -->
             <div class="pull-right">
              <span class="icon" id="icon">
                <i class="fa fa-eye"></i><%= artwork.get_upvotes.size %>
                <%= link_to  like_artwork_path(artwork), method: :get, class: 'data' do %>
                <i class="fa fa-heart"></i>
                <% end %>
                <%= artwork.get_upvotes.size %>
                <i class="fa fa-comment"></i><%= artwork.comments.count %> 
              </span> 
            </div>

          </div>
        </div>
      </div>
    </div>
    <% end %> 
  </div>
</section>
</div>


<script>
            $('.carousel').carousel({
        interval: 10000 //changes the speed
    })
</script>

app/views/artworks/new.html.erb
<div class="col-md-6 col-md-offset-3">
<%= render 'form' %>
</div> 

app/views/artworks/search.html.erb
<div class="col-sm-8 col-sm-offset-4">
 <class="label label-primary"> <%= link_to 'Gallery', artworks_path, class: "label label-primary" %>
  <% Category.all.each do |category| %>
  <%= link_to category.name, artworks_path(category: category.name), class: "label label-primary"%>
  <% end %></class="label">
</div>



<div class="container">
  <section><!-- 
    <div class="page-header"></div> -->
    <div class="row">
      <% @artworks.each do |artwork| %>
      <div class ="col-xs-6 col-sm-6 col-md-3 col-lg-3">
        <div class="panel panel-default">
          <div class="panel-bodyy">
            <%=link_to (image_tag artwork.image.url(:medium), class: 'img-responsive'), artwork %>
          </div>
          <div class="panel-footer">
            <p><%=link_to artwork.caption,artwork,class: 'caption'%></p>
            <hr>
            <p>Artwork by
              <%= link_to artwork.user.username %></p>

              <%#= pluralize(artwork.likes.count, "Like") %>
              <hr>
              <p class="pos"><%= number_to_currency(artwork.price) %><!-- <i class="fa fa-cart-arrow-down fa-2x"></i> --></p>
              <div class="row">
            <!-- <div class="pull-left">
               <p><%= number_to_currency(artwork.price) %></p>
             </div> -->
             <div class="pull-right">
              <span class="icon" id="icon">
                <i class="fa fa-eye"></i><%= artwork.get_upvotes.size %>
                <%= link_to  like_artwork_path(artwork), method: :get, class: 'data' do %>
                <i class="fa fa-heart"></i>
                <% end %>
                <%= artwork.get_upvotes.size %>
                <i class="fa fa-comment"></i><%= artwork.comments.count %> 
              </span> 
            </div>

          </div>
        </div>
      </div>
    </div>
    <% end %> 
  </div>
</section>
</div>

app/views/artworks/show.html.erb
<div class="row">
  <div class="col-md-2">

  </div>

  <div class="col-md-7">
    <div class="row">
      <div class="col-md-12">
        <div id="artwork_show col-md-12">
          <h1>
            <%= @artwork.caption%>
          </h1>
          <h3 class="artistname">
            Shared by
            <%= @artwork.user.username %>
            about
            <%= time_ago_in_words(@artwork.created_at)%>
            ago
          </h3>
          <div class="clearfix">
            <div class="artwork_content1">
              <%= image_tag @artwork.image.url(:large), class: "img-responsive thumbnail" %>
              

            </div>
            
            <div class=" panel panel-default col-md-10">
              <div class="panel-body">

                <div class="col-md-12">
                 <h3>
                  <%= @artwork.description %>
                </h3>
              </div>

              <div class="col-md-12">
                <hr class="col-md-12">
                <span class="pull-left">
                  <% if user_signed_in? %>
                  <% if current_user.artist?  %>
                  <p>
                   <%= link_to  edit_artwork_path(@artwork) do %>
                   <i class="fa fa-pencil-square fa-2x"></i>
                   <% end %>
                   
                   <%= link_to artwork_path(@artwork), method: :delete,
                   data: {confirm: 'Are you sure?'} do %>
                   <i class="fa fa-trash fa-2x"></i>
                   <% end %>
                 </p>
                 <% end %>
                 <p>
                     Share:
                     <%= social_share_button_tag(@artwork.caption) %>
                   </p>
                 <% end %>
               </span>
               <span class="data pull-right">
                <%= link_to  like_artwork_path(@artwork), method: :get, class: 'data' do%>
                <i class="fa fa-heart fa-2x"></i>
                <% end %> <span class="votes"><%= @artwork.get_upvotes.size %></span>
                <i class="fa fa-comment fa-2x"></i>
                <span class="commentt"><%= @artwork.comments.count %></span>
                <span class="price"><%= number_to_currency(@artwork.price)%></span>
                <%= link_to artwork_purchases_path(@artwork), method: :post do %>
                <i class="fa fa-cart-arrow-down fa-2x"></i>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>




    <hr class="col-md-8">
  </div>

</div>

<!-- comments -->
<div class="panel panel-default col-md-10">
  <div id="comment">
    <div class="panel-body">
      <div class="comment_count"><h3><%= pluralize(@artwork.comments.count, "Comment") %></h3></div>

      <div>
        <%= render 'comments/form' %>

      </div>

      <!-- <p>Comments</p> -->
      <br>



      <div class="comment col-md-12">
        <hr>
        <% @comments.each do |comment| %>
        <div class="username"> <h3><strong><%= comment.user.username %></strong></h3></div>
        <div class="content"><p><%= comment.content %></p></div>
        <br>
        <%#= link_to 'Delete', [comment.artwork, comment], method: :delete, data: {confirm: 'Do you want to delete this comment?'}, class: 'btn btn-primary ' %>
        <% end %>


      </div>
    </div>
  </div>
</div>
</div>


<div class="col-md-2 ">
  <div class="row">
    <% @artworks.each do |artwork| %>
    <div class="col-xs-3 col-md-6">
      <%= link_to (image_tag artwork.image.url(:medium), size:'100x100', class: 'thumbnail'), artwork %>

    </div>
    <% end %>
  </div>
</div>

</div>

app/views/comments/_form.html.erb
<div class="col-sm-12" >
<%= simple_form_for ([@artwork, @artwork.comments.build]) do |f| %>
<%= f.input :content %>

<%= f.button :submit, class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Afrikart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav id="main-menu" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag('afrikart.logo.png'), root_path, id: "logo", class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!-- <div class="navbar-left navbar-form" role= "search">
         <%#= search_form_for @search do |f| %>
         <div class="field">
         <%#= f.label :caption_cont, "Search" %>
         <%#= f.search_field :caption_cont %>

         <%#= f.submit %>
         </div>

         
         <% #end %>
      </div> -->
      <ul class="nav navbar-nav">   
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Choose Category <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
            <li><%= link_to category.name, artworks_path(category: category.name)%>
              <% end %></li>

            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to  root_path do %>
            <i class="fa fa-home fa-2x"></i>
            <% end %></li>
            <% if user_signed_in? %>
            <% if current_user.artist %>
              <li><%= link_to  new_artwork_path do %>
               <i class="fa fa-upload fa-2x"></i>
               <% end %>
               <% end %></li>
               <li><%= link_to  destroy_user_session_path, :method => :delete, data: {confirm: 'Do you want to log out?'} do %> 
                <i class="fa fa-sign-out fa-2x"></i>
                <% end %></li>
                <li><%= link_to  edit_user_registration_path do %>
                  <i class="fa fa-user fa-2x"></i> 
                  <% end %></li>
                  <% else %>
                  <li><%= link_to 'Be an artlover!', new_user_registration_path %></li>
                   <li><%= link_to 'Log In', new_user_session_path %></li>        
               <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="clearfix visible-lg"></div>



    <% if admin_signed_in? %>
    <%= link_to'Create Artist. Admin ONLY!', new_admin_user_path %>
    <% end %>


    <% if admin_signed_in? %>
    <%= link_to 'Admin Sign Out', destroy_admin_session_path, method: :delete,
    data: {confirm: 'Are you sure?'} %>
    <%= link_to 'View artists. Admin ONLY!', admin_users_path %>
    <% end %>


<!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->

  <div class="space">
    <%= yield %>
  </div>


</body>
</html>

app/views/purchases/show.html.erb
<p>Purchases</p>

<%= link_to (image_tag @artwork.image.url(:thumb)), artwork_path(@artwork) %>